### ISSUE TITLE
Text is doubled on page "Learn more"

### ISSUE THREAD

**Issue by VLNTNO** [gosub-browser/gosub.io-website#17]
Hello,

I have read the "Learn More" page and the content is doubled : 

* paragraphs 1 and 3 are identical
* paragraphs 2 and 4 are identical

Please delete the unnecessary paragraphs.

Regards
Valentin

**Comment by Sharktheone** [comment]
This was fixed by #15 however we forgot to do the deployment. And now we didn't want to mess with it. But thanks for the issue!

**Comment by jaytaph** [comment]
@VLNTNO Thanks for the reminder!  I've tagged the new release and it's deployed..  (we don't deploy on main, but rather on tags)..  It should be correct now.

**Comment by VLNTNO** [comment]
No worries. Bonjour I'm  glad to help.

Wishing you the best for this project !
